[package]
name = "cooklang-sync-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "client"

[dependencies]
diesel = { version = "2.1.4", features = ["sqlite", "time", "r2d2"] }
diesel_migrations = { version = "2.1.0", features = ["sqlite"] }
env_logger = "0.11.0"
futures = "0.3.30"
log = "0.4.20"
notify = "6.1.1"
notify-debouncer-mini = "0.4.1"
quick_cache = "0.4.1"
reqwest = { version = "0.11.24", features = ["json", "multipart"] }
rusqlite = { version = "0.30.0", features = ["bundled"] }
serde = "1.0.196"
serde_json = "1.0.113"
sha2 = "0.10.8"
thiserror = "1.0.57"
time = { version = "0.3.31", features = ["std"] }
tokio = { version = "1.35.1", features = ["time", "fs", "macros", "rt-multi-thread"] }
uniffi = "0.26.1"
uuid = { version = "1.7.0", features = ["v4"] }
walkdir = "2.4.0"
openssl = { version = "0.10", features = ["vendored"] }

[lib]
crate-type = ["cdylib", "staticlib"]


[[bin]]
# workaround: https://mozilla.github.io/uniffi-rs/tutorial/foreign_language_bindings.html#creating-the-bindgen-binary
# This can be whatever name makes sense for your project, but the rest of this tutorial assumes uniffi-bindgen.
name = "uniffi-bindgen"
path = "src/uniffi-bindgen.rs"
required-features = ["uniffi/cli"]
