[target.x86_64-linux-android]
linker = "x86_64-linux-android29-clang"
ar = "llvm-ar"
rustflags = [
    "-L/Users/dubadub/Library/Android/sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang/17.0.2/lib/linux/",
    "-lstatic=clang_rt.builtins-x86_64-android"
]

[target.i686-linux-android]
linker = "i686-linux-android29-clang"
ar = "llvm-ar"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi29-clang"
ar = "llvm-ar"

[target.aarch64-linux-android]
linker = "aarch64-linux-android29-clang"
ar = "llvm-ar"
